package cn.edu.qhu.tes.entities;

public enum ProblemType {
	//因为这个是枚举类型，所以写好之后就不可以调整顺序，因为它在数据库中存的是数值
	ORIENTATION_SINGLE_SELECT_NO_OTHER,//0
	ORIENTATION_SINGLE_SELECT_HAS_OTHER,//1
	VERTICAL_SINGLE_SELECT_NO_OTHER,//2
	VERTICAL_SINGLE_SELECT_HAS_OTHER,//3
	ORIENTATION_MUTIPLE_SELECT_NO_OTHER,//4
	ORIENTATION_MUTIPLE_SELECT_HAS_OTHER,//5
	VERTICAL_MUTIPLE_SELECT_NO_OTHER,//6
	VERTICAL_MUTIPLE_SELECT_HAS_OTHER,//7
	
}
